vim.opt.shell = "/bin/bash" -- Use bash instead of fish (faster for nvim)

require "_keymaps"
require "_options"
require "_plugins"
require "_colorscheme"
require "lsp"
require "_cmp"
require "_lualine"
require "_tabnine"
require "_telescope"
require "_autopairs"
require "_treesitter"
require "_comment"
require "_luasnip"
require "_illuminate"
